---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)

setwd("M:/Documents/Autocorrelation")
```

# Alex's data

```{r}
dat <- read.table("data/2022-09-14 keystroke detail.psv", header = TRUE, sep = "|", comment.char = "")
head(dat)
```

```{r}
table(dat$keypress_type)
```

```{r}
table(dat$sessionTimeZone)
```




```{r}
hist(dat$sampleNumber)
```

```{r}
length(unique(dat$sessionTimestamp))
```

```{r}
dat %>%
  mutate(date = as.POSIXct(sessionTimestamp, origin="1970-01-01", tz="Asia/Taipei")) %>%
  group_by(sessionTimestamp) %>%
  summarise(
    duration = sessionDuration[1],
    sumUnknown1 = sum(X.Unknown1., na.rm = TRUE),
    sumUnknown2 = sum(X.Unknown2., na.rm = TRUE),
    alphanum = sum(keypress_type == "alphanum") / n(),
    autocorrect = sum(keypress_type == "autocorrection") / n(),
    backspace = sum(keypress_type == "backspace") / n(),
    date = date[1]
  )
```

```{r}
dat %>%
  group_by(sessionTimestamp) %>%
  group_modify(function (x, y) {
    if (nrow(x) == 1) {
      return(data.frame())
    }
    
    sel <- 1:(nrow(x)-1) # Original selection
    lagged_sel <- 2:nrow(x) # Lagged selection
    x[sel,]$keypress_type <- paste(x[sel,]$keypress_type, x[lagged_sel,]$keypress_type, sep = "-")
    x[sel,]
  })
```


```{r}
dat
```

# Suicidal women data

```{r}
dat_kp <- read.csv("data/User_3009_keypressDataMetrics.csv")
dat_kp
```

```{r}
dat_acc <- read.csv("data/User_3009_accelData.csv")
dat_acc
```

```{r}
dat_kp <- dat_kp %>%
  mutate(
    date = as.Date(date, format = "%Y-%m-%d"),
    keypressTimestampLocal = as.POSIXct(keypressTimestampLocal, format = "%Y-%m-%d %H:%M:%OS"),
    sessionTimestampLocal = as.POSIXct(keypressTimestampLocal, format = "%Y-%m-%d %H:%M:%OS")
  )
```

```{r}
dat_kp_avg <- dat_kp %>%
  mutate(hour = format(keypressTimestampLocal, "%H")) %>%
  group_by(hour, sessionNumber) %>%
  summarise(medianIKD = median(IKD, na.rm = TRUE)) %>%
  group_by(hour) %>%
  summarise(meanIKD = mean(medianIKD, na.rm = TRUE))
  
plot(dat_kp_avg$hour, dat_kp_avg$meanIKD, type = "b")
```

Session level

```{r}
dat_ses <- dat_kp %>%
  group_by(sessionNumber) %>%
  mutate(
    autocorrectRate = sum(keypress_type == "autocorrection") / n(),
    backspaceRate = sum(keypress_type == "backspace") / n(),
    totalKeyPresses = n()
  ) %>%
  filter(keypress_type == "alphanum", previousKeyType == "alphanum") %>%
  summarise(
    medianIKD = median(IKD, na.rm = TRUE),
    percent95IKD = quantile(IKD, .95, na.rm = TRUE),
    madIKD = mad(IKD, na.rm = TRUE),
    autocorrectRate = autocorrectRate[1],
    backspaceRate = backspaceRate[1],
    sessionTimestampLocal = sessionTimestampLocal[1],
    totalKeyPresses = totalKeyPresses[1]
  )

dat_ses
```

```{r}
with(dat_ses, {
  plot(medianIKD, madIKD)
})
```

